"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-c($b!cga$4%iw63ue4j!rd=nfe71vb($*1tmazacli8o&9w4ya'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
# Django 기본 앱들을 모아 둔 리스트
DJANGO_APPS = [
    'django.contrib.admin',         # 관리자 사이트
    'django.contrib.auth',          # 인증/권한(로그인, 권한 관리)
    'django.contrib.contenttypes',  # 콘텐츠 타입(권한 시스템에 사용)
    'django.contrib.sessions',      # 세션 프레임워크
    'django.contrib.messages',      # 메시지 프레임워크(알림 등)
    'django.contrib.staticfiles',   # 정적 파일(css, js, 이미지) 관리
]

# 내가 만든(또는 프로젝트 안에서 직접 개발하는) 앱 리스트
OWN_APPS = [
    'blog',  # 블로그 기능을 담당하는 Django 앱
    'member',
]

# 외부 라이브러리 (Django 기준)
THIRD_PARTY_APPS = [
    'django_extensions',
]

# 실제로 Django가 인식해서 로딩할 앱 목록
# 기본 Django 앱 + 내가 만든 앱들을 합쳐서 INSTALLED_APPS 로 등록
INSTALLED_APPS = DJANGO_APPS + OWN_APPS + THIRD_PARTY_APPS

# 각 HTTP 요청/응답 사이에서 순서대로 실행되는 미들웨어 목록
# (위에서 아래로 처리됨)
MIDDLEWARE = [
    # 보안 관련 기본 헤더 추가, HTTP/SECURE_* 설정 적용 등 전반적인 보안 강화
    'django.middleware.security.SecurityMiddleware',

    # 세션 ID를 쿠키로 주고받으면서 request.session 객체를 사용할 수 있게 해 줌
    'django.contrib.sessions.middleware.SessionMiddleware',

    # 공통적인 요청/응답 처리 (예: URL 정규화, HEAD 요청 처리, 기타 편의 기능)
    'django.middleware.common.CommonMiddleware',

    # CSRF 토큰을 검증하여 POST/PUT/DELETE 등의 요청이 위조되지 않았는지 확인
    'django.middleware.csrf.CsrfViewMiddleware',

    # 인증된 사용자 정보를 request.user에 주입하고 로그인/로그아웃 상태를 관리
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    # 장고 메시지 프레임워크가 임시 알림 메시지를 쿠키/세션에 저장·조회할 수 있게 함
    'django.contrib.messages.middleware.MessageMiddleware',

    # 클릭재킹(clickjacking) 공격을 막기 위해 X-Frame-Options 응답 헤더를 설정
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# Admin 언어 변경
LANGUAGE_CODE = 'ko-KR'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# login
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/login/'
LOGOUT_REDIRECT_URL = '/'