# Generated by Django 5.0.4 on 2025-12-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('free', '자유'), ('travel', '여행'), ('study', '공부'), ('dev', '개발'), ('daily', '일상'), ('review', '리뷰'), ('food', '음식'), ('health', '운동'), ('career', '진로'), ('etc', '기타')], max_length=10, verbose_name='category')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
        ),
    ]
